CREATE DATABASE LOGINJB;

USE LOGINJB;

CREATE TABLE USERS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    USER VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(21) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(25) NOT NULL,
    LAST_NAME VARCHAR(25) NOT NULL
);

INSERT INTO USERS(USER,PASSWORD,EMAIL,FIRST_NAME,LAST_NAME) 
VALUES ("JEBT28","18100152","18100152@NLAREDO.COM","JUAN","TOBON"); 
VALUES ("INVITADO","INV123","INVITADO@NLAREDO.COM","USUARIO","INVITADO"); 